name = "quay-cloudflare-cdn-worker"
type = "webpack"

account_id = "2398e241c821b33df663d5c6b87916b9"
workers_dev = true
route = "https://cdn01.quaydev.org/*"
zone_id = "e0f1cdd66f0bba354824a197a7622d85"
compatibility_date = "2022-04-22"

[vars]
QUAY_PRIMARY_REGION="us-east-1"
QUAY_PRIMARY_S3_BUCKET = "cloudflare-poc-quay-storage"
QUAY_SECONDARY_REGION = "us-east-2"
QUAY_SECONDARY_S3_BUCKET = "cloudflare-poc-quay-storage"

CLOUDFLARE_PUBLIC_KEY = '''
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt0SG2ZRol55hL8DzyPBS
a/dgS7xKTYN9TTpEjZUxjlAexqwHnTLRHsScwLVcAfn74UDNT9LKfel1ZDRY1pr8
aCw/NOL61nzaHIdmtotWh/U2eDn9cLt0c2bSB3AAZJZLUQRvICO/jcl0efZpt8TL
ZnT8hGpsOrWnu5RWgXbXe2/KrpTzsmS12VKAdvcAVki2o0L8N7NvcHS7SREpV6ar
KvKu1wZ0DDDnPaFihqNbBkZIDOUPdMka9AJEwas2jvtUuuUyv8bEvyOEhCyCEwqm
qFc4G5TXqPEguI+IcNe7HJiLll7+0VK/0LYbyhWKMXM4Xy94kfXW4cNo15V2qgvU
TwIDAQAB
-----END PUBLIC KEY-----
'''

CACHE_TTL = 60
